### ISSUE TITLE
Add option to refrain from overriding existing variables

### ISSUE THREAD

**Issue by sneakertack** [sneakertack/nvar#3]
The module's current default behaviour is to override a variable if it has already been previously set, some people might prefer it not to do so.

**Comment by einnjo** [comment]
This would be great, most of our other tooling works the opposite way. (env takes precedence)

**Comment by sneakertack** [comment]
Okay! Since there was demand for it, I've just written and published v1.3.0 to npm. This adds an `override` configuration option which can be set to `'all'`, `'empty'`, or `'none'`.

More details are available in the API section of the readme - for your case it sounds like you'd want to set it to `'none'` (or maybe `'empty'` - they're almost the same).

**Comment by einnjo** [comment]
Awesome! I'll give it a spin.
